//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
namespace Sedansynergy.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.DBserviceSoap")]
    public interface DBserviceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertData", ReplyAction="*")]
        System.Threading.Tasks.Task<Sedansynergy.ServiceReference1.InsertDataResponse> InsertDataAsync(Sedansynergy.ServiceReference1.InsertDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/logincheck", ReplyAction="*")]
        System.Threading.Tasks.Task<Sedansynergy.ServiceReference1.logincheckResponse> logincheckAsync(Sedansynergy.ServiceReference1.logincheckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setride", ReplyAction="*")]
        System.Threading.Tasks.Task<Sedansynergy.ServiceReference1.setrideResponse> setrideAsync(Sedansynergy.ServiceReference1.setrideRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchride", ReplyAction="*")]
        System.Threading.Tasks.Task<Sedansynergy.ServiceReference1.searchrideResponse> searchrideAsync(Sedansynergy.ServiceReference1.searchrideRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/arraything", ReplyAction="*")]
        System.Threading.Tasks.Task arraythingAsync(int currdate, int curryear, int currmonth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/arrlength", ReplyAction="*")]
        System.Threading.Tasks.Task<int> arrlengthAsync(int currdate);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertData", Namespace="http://tempuri.org/", Order=0)]
        public Sedansynergy.ServiceReference1.InsertDataRequestBody Body;
        
        public InsertDataRequest() {
        }
        
        public InsertDataRequest(Sedansynergy.ServiceReference1.InsertDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long phonenumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string brand;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string model;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int mileage;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string variant;
        
        public InsertDataRequestBody() {
        }
        
        public InsertDataRequestBody(string username, string email, long phonenumber, string password, string brand, string model, int mileage, string variant) {
            this.username = username;
            this.email = email;
            this.phonenumber = phonenumber;
            this.password = password;
            this.brand = brand;
            this.model = model;
            this.mileage = mileage;
            this.variant = variant;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Sedansynergy.ServiceReference1.InsertDataResponseBody Body;
        
        public InsertDataResponse() {
        }
        
        public InsertDataResponse(Sedansynergy.ServiceReference1.InsertDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int InsertDataResult;
        
        public InsertDataResponseBody() {
        }
        
        public InsertDataResponseBody(int InsertDataResult) {
            this.InsertDataResult = InsertDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logincheckRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logincheck", Namespace="http://tempuri.org/", Order=0)]
        public Sedansynergy.ServiceReference1.logincheckRequestBody Body;
        
        public logincheckRequest() {
        }
        
        public logincheckRequest(Sedansynergy.ServiceReference1.logincheckRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class logincheckRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public logincheckRequestBody() {
        }
        
        public logincheckRequestBody(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logincheckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logincheckResponse", Namespace="http://tempuri.org/", Order=0)]
        public Sedansynergy.ServiceReference1.logincheckResponseBody Body;
        
        public logincheckResponse() {
        }
        
        public logincheckResponse(Sedansynergy.ServiceReference1.logincheckResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class logincheckResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int logincheckResult;
        
        public logincheckResponseBody() {
        }
        
        public logincheckResponseBody(int logincheckResult) {
            this.logincheckResult = logincheckResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setrideRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setride", Namespace="http://tempuri.org/", Order=0)]
        public Sedansynergy.ServiceReference1.setrideRequestBody Body;
        
        public setrideRequest() {
        }
        
        public setrideRequest(Sedansynergy.ServiceReference1.setrideRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class setrideRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string startingplace;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string destination;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal startingplacelat;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal startingplacelong;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal destlat;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public decimal destlong;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int hrs;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int min;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int day;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int month;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int year;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string mode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public int cap;
        
        public setrideRequestBody() {
        }
        
        public setrideRequestBody(string startingplace, string destination, decimal startingplacelat, decimal startingplacelong, decimal destlat, decimal destlong, int hrs, int min, int day, int month, int year, string email, string mode, int cap) {
            this.startingplace = startingplace;
            this.destination = destination;
            this.startingplacelat = startingplacelat;
            this.startingplacelong = startingplacelong;
            this.destlat = destlat;
            this.destlong = destlong;
            this.hrs = hrs;
            this.min = min;
            this.day = day;
            this.month = month;
            this.year = year;
            this.email = email;
            this.mode = mode;
            this.cap = cap;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setrideResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setrideResponse", Namespace="http://tempuri.org/", Order=0)]
        public Sedansynergy.ServiceReference1.setrideResponseBody Body;
        
        public setrideResponse() {
        }
        
        public setrideResponse(Sedansynergy.ServiceReference1.setrideResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class setrideResponseBody {
        
        public setrideResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchrideRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchride", Namespace="http://tempuri.org/", Order=0)]
        public Sedansynergy.ServiceReference1.searchrideRequestBody Body;
        
        public searchrideRequest() {
        }
        
        public searchrideRequest(Sedansynergy.ServiceReference1.searchrideRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class searchrideRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string startingplace;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string destination;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal startingplacelat;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal startingplacelong;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal destlat;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public decimal destlong;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int hrs;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int min;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int day;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int month;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int year;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string mode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public int cap;
        
        public searchrideRequestBody() {
        }
        
        public searchrideRequestBody(string startingplace, string destination, decimal startingplacelat, decimal startingplacelong, decimal destlat, decimal destlong, int hrs, int min, int day, int month, int year, string email, string mode, int cap) {
            this.startingplace = startingplace;
            this.destination = destination;
            this.startingplacelat = startingplacelat;
            this.startingplacelong = startingplacelong;
            this.destlat = destlat;
            this.destlong = destlong;
            this.hrs = hrs;
            this.min = min;
            this.day = day;
            this.month = month;
            this.year = year;
            this.email = email;
            this.mode = mode;
            this.cap = cap;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchrideResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchrideResponse", Namespace="http://tempuri.org/", Order=0)]
        public Sedansynergy.ServiceReference1.searchrideResponseBody Body;
        
        public searchrideResponse() {
        }
        
        public searchrideResponse(Sedansynergy.ServiceReference1.searchrideResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class searchrideResponseBody {
        
        public searchrideResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DBserviceSoapChannel : Sedansynergy.ServiceReference1.DBserviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DBserviceSoapClient : System.ServiceModel.ClientBase<Sedansynergy.ServiceReference1.DBserviceSoap>, Sedansynergy.ServiceReference1.DBserviceSoap {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DBserviceSoapClient() : 
                base(DBserviceSoapClient.GetDefaultBinding(), DBserviceSoapClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.DBserviceSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DBserviceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(DBserviceSoapClient.GetBindingForEndpoint(endpointConfiguration), DBserviceSoapClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DBserviceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DBserviceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DBserviceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DBserviceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DBserviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sedansynergy.ServiceReference1.InsertDataResponse> Sedansynergy.ServiceReference1.DBserviceSoap.InsertDataAsync(Sedansynergy.ServiceReference1.InsertDataRequest request) {
            return base.Channel.InsertDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sedansynergy.ServiceReference1.InsertDataResponse> InsertDataAsync(string username, string email, long phonenumber, string password, string brand, string model, int mileage, string variant) {
            Sedansynergy.ServiceReference1.InsertDataRequest inValue = new Sedansynergy.ServiceReference1.InsertDataRequest();
            inValue.Body = new Sedansynergy.ServiceReference1.InsertDataRequestBody();
            inValue.Body.username = username;
            inValue.Body.email = email;
            inValue.Body.phonenumber = phonenumber;
            inValue.Body.password = password;
            inValue.Body.brand = brand;
            inValue.Body.model = model;
            inValue.Body.mileage = mileage;
            inValue.Body.variant = variant;
            return ((Sedansynergy.ServiceReference1.DBserviceSoap)(this)).InsertDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sedansynergy.ServiceReference1.logincheckResponse> Sedansynergy.ServiceReference1.DBserviceSoap.logincheckAsync(Sedansynergy.ServiceReference1.logincheckRequest request) {
            return base.Channel.logincheckAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sedansynergy.ServiceReference1.logincheckResponse> logincheckAsync(string email, string password) {
            Sedansynergy.ServiceReference1.logincheckRequest inValue = new Sedansynergy.ServiceReference1.logincheckRequest();
            inValue.Body = new Sedansynergy.ServiceReference1.logincheckRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((Sedansynergy.ServiceReference1.DBserviceSoap)(this)).logincheckAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sedansynergy.ServiceReference1.setrideResponse> Sedansynergy.ServiceReference1.DBserviceSoap.setrideAsync(Sedansynergy.ServiceReference1.setrideRequest request) {
            return base.Channel.setrideAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sedansynergy.ServiceReference1.setrideResponse> setrideAsync(string startingplace, string destination, decimal startingplacelat, decimal startingplacelong, decimal destlat, decimal destlong, int hrs, int min, int day, int month, int year, string email, string mode, int cap) {
            Sedansynergy.ServiceReference1.setrideRequest inValue = new Sedansynergy.ServiceReference1.setrideRequest();
            inValue.Body = new Sedansynergy.ServiceReference1.setrideRequestBody();
            inValue.Body.startingplace = startingplace;
            inValue.Body.destination = destination;
            inValue.Body.startingplacelat = startingplacelat;
            inValue.Body.startingplacelong = startingplacelong;
            inValue.Body.destlat = destlat;
            inValue.Body.destlong = destlong;
            inValue.Body.hrs = hrs;
            inValue.Body.min = min;
            inValue.Body.day = day;
            inValue.Body.month = month;
            inValue.Body.year = year;
            inValue.Body.email = email;
            inValue.Body.mode = mode;
            inValue.Body.cap = cap;
            return ((Sedansynergy.ServiceReference1.DBserviceSoap)(this)).setrideAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sedansynergy.ServiceReference1.searchrideResponse> Sedansynergy.ServiceReference1.DBserviceSoap.searchrideAsync(Sedansynergy.ServiceReference1.searchrideRequest request) {
            return base.Channel.searchrideAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sedansynergy.ServiceReference1.searchrideResponse> searchrideAsync(string startingplace, string destination, decimal startingplacelat, decimal startingplacelong, decimal destlat, decimal destlong, int hrs, int min, int day, int month, int year, string email, string mode, int cap) {
            Sedansynergy.ServiceReference1.searchrideRequest inValue = new Sedansynergy.ServiceReference1.searchrideRequest();
            inValue.Body = new Sedansynergy.ServiceReference1.searchrideRequestBody();
            inValue.Body.startingplace = startingplace;
            inValue.Body.destination = destination;
            inValue.Body.startingplacelat = startingplacelat;
            inValue.Body.startingplacelong = startingplacelong;
            inValue.Body.destlat = destlat;
            inValue.Body.destlong = destlong;
            inValue.Body.hrs = hrs;
            inValue.Body.min = min;
            inValue.Body.day = day;
            inValue.Body.month = month;
            inValue.Body.year = year;
            inValue.Body.email = email;
            inValue.Body.mode = mode;
            inValue.Body.cap = cap;
            return ((Sedansynergy.ServiceReference1.DBserviceSoap)(this)).searchrideAsync(inValue);
        }
        
        public System.Threading.Tasks.Task arraythingAsync(int currdate, int curryear, int currmonth) {
            return base.Channel.arraythingAsync(currdate, curryear, currmonth);
        }
        
        public System.Threading.Tasks.Task<int> arrlengthAsync(int currdate) {
            return base.Channel.arrlengthAsync(currdate);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.DBserviceSoap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.DBserviceSoap)) {
                return new System.ServiceModel.EndpointAddress("http://teammfap.somee.com/DBservice.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return DBserviceSoapClient.GetBindingForEndpoint(EndpointConfiguration.DBserviceSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return DBserviceSoapClient.GetEndpointAddress(EndpointConfiguration.DBserviceSoap);
        }
        
        public enum EndpointConfiguration {
            
            DBserviceSoap,
        }
    }
}
